# 日志级别
logging:
  level: "debug" # info | debug

# 上游池
upstream:
  enable: true
  http: ["http://127.0.0.1:8081", "http://127.0.0.1:8082"]           # e.g. ["http://127.0.0.1:3128"]  
  socks5: ["socks5://127.0.0.1:1081", "socks5://127.0.0.1:1082"]      # e.g. ["socks5://127.0.0.1:1081"]  
  algo: least_conn # round_robin(轮询) | least_conn(最少连接数)
  health:
    interval: 5s   # e.g. 10s
    timeout: 2s     # e.g. 5s

# http 代理
http:
  enable: true
  listen: ":8080"   # e.g. ":8080"

# socks5 代理
socks5:
  enable: true
  listen: ":1080"   # e.g. ":1080"

# 连接配置
timeouts:
  dial: 10s         # e.g. 10s
  keepAlive: 30s    # e.g. 30s
  tlsHandshake: 10s # e.g. 10s
  respHeader: 30s   # e.g. 30s
  idleConn: 90s     # e.g. 90s

# 管理 API + 面板
admin:
  enable: true
  listen: ":8088"

# 访问控制规则
acl:
  whitelist: ["*.edu", "*.gov"]
  blacklist: ["bad.com"]
  tld: [".xxx", ".adult"]
  keywords: ["ads", "porn", "sex", "track"]

# 速率限制
ratelimit:
  global_qps: 0
  per_ip_qps: 0
