// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get runtime stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/metrics.StatsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "metrics.StatsResponse": {
            "type": "object",
            "properties": {
                "avgLatencyMs": {
                    "type": "integer",
                    "example": 18
                },
                "blockRate": {
                    "type": "number",
                    "example": 0.13
                },
                "concurrent": {
                    "type": "integer",
                    "example": 42
                },
                "p95LatencyMs": {
                    "type": "integer",
                    "example": 45
                },
                "qps": {
                    "type": "number",
                    "example": 12.3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Proxy Server API",
	Description:      "HTTP代理 + 规则拦截 + 指标接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
